package gui;

import tretmani.TipTretmana;
import tretmani.Tretmani;
import tretmani.VrstaTretmana;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.Duration;
import java.util.ArrayList;

public class DodavanjeVrste extends JFrame {
    private JComboBox cbTip;
    private JTextField tfNaziv;
    private JTextField tfCena;
    private JButton napraviButton;
    private JTextField tfTrajanje;
    private JPanel vrstaPanel;

    public DodavanjeVrste() {
        setContentPane(vrstaPanel);
        setTitle("Nova vrsta tretmana");
        setSize(500, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ArrayList<Integer> ids = new ArrayList<Integer>();
        for (TipTretmana tip : Tretmani.sviTipoviTretmana.values()) {
            cbTip.addItem(tip.getNazivTipaTretmana());
            ids.add(tip.idGetter());
        }

        setVisible(true);

        napraviButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String naziv = tfNaziv.getText();
                TipTretmana tip = Tretmani.sviTipoviTretmana.get(ids.get(cbTip.getSelectedIndex()));
                int cena = Integer.parseInt(tfCena.getText());
                Duration trajanje = Duration.ofMinutes(Integer.parseInt(tfTrajanje.getText()));

                VrstaTretmana tretman = new VrstaTretmana(naziv, tip, cena, trajanje);
                boolean uspeh = Tretmani.dodajVrstuTretmana(tretman);

                if (uspeh) {
                    JOptionPane.showMessageDialog(null, "Dodavanje uspesno", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Vrsta vec postoji", "Registracija neuspesna", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        vrstaPanel = new JPanel();
        vrstaPanel.setLayout(new GridBagLayout());
        cbTip = new JComboBox();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vrstaPanel.add(cbTip, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vrstaPanel.add(spacer1, gbc);
        tfNaziv = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vrstaPanel.add(tfNaziv, gbc);
        tfCena = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vrstaPanel.add(tfCena, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Tip tretmana:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        vrstaPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Naziv vrste tretmana:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        vrstaPanel.add(label2, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        vrstaPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        vrstaPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        vrstaPanel.add(spacer4, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Cena:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        vrstaPanel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Trajanje u minutima:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        vrstaPanel.add(label4, gbc);
        napraviButton = new JButton();
        napraviButton.setText("Napravi");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vrstaPanel.add(napraviButton, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        vrstaPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vrstaPanel.add(spacer6, gbc);
        tfTrajanje = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vrstaPanel.add(tfTrajanje, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return vrstaPanel;
    }
}
