package gui;

import org.jdatepicker.JDateComponentFactory;
import org.jdatepicker.JDatePicker;
import org.jdatepicker.impl.UtilDateModel;
import tretmani.TipTretmana;
import tretmani.Tretmani;
import tretmani.ZakazanTretman;

import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.GregorianCalendar;
import java.util.Properties;

public class IzvestajOtkazivanje extends JFrame {
    private JScrollPane tabelaPanel;
    private JPanel OtkazivanjePanel;

    public IzvestajOtkazivanje() {
        UtilDateModel dateModel = new UtilDateModel();
        Properties properties = new Properties();

        JDateComponentFactory fabrika = new JDateComponentFactory();
        JDatePicker datePickerOd = fabrika.createJDatePicker();
        JDatePicker datePickerDo = fabrika.createJDatePicker();

        Object[] components = {"Od:", datePickerOd, "Do:", datePickerDo};
        Object[] optionsDate = {"OK", "Cancel"};
        LocalDate datumOd = null;
        LocalDate datumDo = null;


        int option = JOptionPane.showOptionDialog(null, components, "Date Picker", JOptionPane.DEFAULT_OPTION,
                JOptionPane.PLAIN_MESSAGE, null, optionsDate, optionsDate[0]);
        if (option == JOptionPane.OK_OPTION) {
            GregorianCalendar selectedDate = (GregorianCalendar) datePickerOd.getModel().getValue();
            datumOd = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            selectedDate = (GregorianCalendar) datePickerDo.getModel().getValue();
            datumDo = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            System.out.println("Selected date: " + datumOd + " " + datumDo);
        } else {
            System.out.println("User cancelled.");
        }

        setTitle("Izvestaj statusi");
        setSize(500, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        String[] header = {"Status", "Broj"};
        Object[][] sadrzaj = new Object[5][2];
        int i = 0;
        for (ZakazanTretman.statusTretmana status : ZakazanTretman.statusTretmana.values()) {
            ;
            sadrzaj[i][0] = status;
            sadrzaj[i][1] = Tretmani.brojStatus(status, datumOd, datumDo);
            i++;
        }

        DefaultTableModel model = new DefaultTableModel(sadrzaj, header) {
            public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
            }
        };

        model.setColumnIdentifiers(header);
        JTable tabelaIspis = new JTable(model);


        tabelaPanel.setViewportView(tabelaIspis);
        setContentPane(OtkazivanjePanel);
        tabelaIspis.setFocusable(false);
        tabelaIspis.setRowSelectionAllowed(true);
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        OtkazivanjePanel = new JPanel();
        OtkazivanjePanel.setLayout(new GridBagLayout());
        tabelaPanel = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        OtkazivanjePanel.add(tabelaPanel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        OtkazivanjePanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        OtkazivanjePanel.add(spacer2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return OtkazivanjePanel;
    }
}
