package gui;

import korisnici.Korisnici;
import tretmani.Tretmani;
import tretmani.ZakazanTretman;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;


public class KlijentPrikazNeizvrsenih extends JFrame {
    private JScrollPane tabelaPanelNeizvrseni;
    private JPanel neizvrseniPanel;
    private JButton otkaziButton;

    public KlijentPrikazNeizvrsenih() {
        setTitle("Izvrseni Tretmani");
        setSize(500, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ArrayList<ZakazanTretman> zakazani = Tretmani.prikaziBuduceTretmane(Korisnici.trenutniKorisnik);
        String[] header = {"Naziv tretmana", "Datum i vreme", "Kozmeticar", "Cena", "Status"};
        Object[][] sadrzaj = new Object[zakazani.size()][5];
        int i = 0;
        for (ZakazanTretman zakazan : zakazani) {
            sadrzaj[i][0] = zakazan.getNaziv();
            sadrzaj[i][1] = zakazan.getDatum_i_vreme().format(DateTimeFormatter.ofPattern("dd.MM.yyyy. HH:mm"));
            sadrzaj[i][2] = zakazan.getKozmeticar().getIme() + " " + zakazan.getKozmeticar().getPrezime();
            sadrzaj[i][3] = zakazan.getCena();
            sadrzaj[i][4] = zakazan.getStatus();
            i++;
        }

        DefaultTableModel model = new DefaultTableModel(sadrzaj, header) {
            public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
            }
        };

        model.setColumnIdentifiers(header);
        JTable tabelaIspis = new JTable(model);
        tabelaPanelNeizvrseni.setViewportView(tabelaIspis);
        setContentPane(neizvrseniPanel);
        tabelaIspis.setFocusable(false);
        tabelaIspis.setRowSelectionAllowed(true);
        setVisible(true);


        otkaziButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ZakazanTretman tretman = zakazani.get(tabelaIspis.getSelectedRow());
                int choice = JOptionPane.showConfirmDialog(null, "Da li ste sigurni?", "Potvrda", JOptionPane.YES_NO_OPTION);
                if (choice == JOptionPane.YES_OPTION) {
                    Tretmani.otkazi(tretman);
                    JOptionPane.showMessageDialog(null, "Otkazivanje uspesno", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
                    dispose();

                } else {
                    System.out.println("Cancelled.");
                }
            }
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        neizvrseniPanel = new JPanel();
        neizvrseniPanel.setLayout(new GridBagLayout());
        tabelaPanelNeizvrseni = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        neizvrseniPanel.add(tabelaPanelNeizvrseni, gbc);
        otkaziButton = new JButton();
        otkaziButton.setText("Otkazi  tretman");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        neizvrseniPanel.add(otkaziButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        neizvrseniPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        neizvrseniPanel.add(spacer2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return neizvrseniPanel;
    }

}
