package gui;

import korisnici.Korisnici;
import tretmani.Tretmani;
import tretmani.ZakazanTretman;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

public class KlijentPrikazIzvrsenih extends JFrame {
    private JPanel ispisIzvrsenihK;
    private JScrollPane tabelaPanel;
    private JLabel lblTroskovi;

    public KlijentPrikazIzvrsenih() {
        setTitle("Izvrseni Tretmani");
        setSize(500, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ArrayList<ZakazanTretman> zakazani = Tretmani.odrediPrethodneTretmane(Korisnici.trenutniKorisnik);
        String[] header = {"Naziv tretmana", "Datum i vreme", "Kozmeticar", "Trosak", "Status"};
        Object[][] sadrzaj = new Object[zakazani.size()][5];
        int i = 0;
        int ukupniTroskovi = 0;
        for (ZakazanTretman zakazan : zakazani) {
            sadrzaj[i][0] = zakazan.getNaziv();
            sadrzaj[i][1] = zakazan.getDatum_i_vreme().format(DateTimeFormatter.ofPattern("dd.MM.yyyy. HH:mm"));
            sadrzaj[i][2] = zakazan.getKozmeticar().getIme() + " " + zakazan.getKozmeticar().getPrezime();
            if (zakazan.getStatus() == ZakazanTretman.statusTretmana.OTKAZAO_KLIJENT) {
                sadrzaj[i][3] = zakazan.getCena() / 10;
            } else if (zakazan.getStatus() == ZakazanTretman.statusTretmana.OTKAZAO_SALON) {
                sadrzaj[i][3] = 0;
            } else {
                sadrzaj[i][3] = zakazan.getCena();
            }
            ukupniTroskovi += (int) sadrzaj[i][3];
            sadrzaj[i][4] = zakazan.getStatus();
            i++;
        }
        lblTroskovi.setText("Ukupni troskovi: " + ukupniTroskovi);
        DefaultTableModel model = new DefaultTableModel(sadrzaj, header) {
            public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
            }
        };
        ;
        model.setColumnIdentifiers(header);
        JTable tabelaIspis = new JTable(model);
        tabelaPanel.setViewportView(tabelaIspis);
        setContentPane(ispisIzvrsenihK);
        tabelaIspis.setFocusable(false);
        tabelaIspis.setRowSelectionAllowed(false);
        setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ispisIzvrsenihK = new JPanel();
        ispisIzvrsenihK.setLayout(new GridBagLayout());
        tabelaPanel = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        ispisIzvrsenihK.add(tabelaPanel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ispisIzvrsenihK.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        ispisIzvrsenihK.add(spacer2, gbc);
        lblTroskovi = new JLabel();
        lblTroskovi.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        ispisIzvrsenihK.add(lblTroskovi, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ispisIzvrsenihK;
    }

}
