package gui;

import korisnici.Korisnici;
import tretmani.Tretmani;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class KorisnikMeni extends JFrame {
    private JButton pregledIzvrsenihTretmanaButton;
    private JButton odjavaButton;
    private JLabel lbLoyalty;
    private JButton zakaziTretmanButton;
    private JButton pregledZakazanihTretmanaButton;
    private JLabel lbWelcome;
    private JPanel kMeniPanel;
    private JLabel lblCard;

    public KorisnikMeni() {
        lbLoyalty.setText("Prikupljeno bodova: " + Korisnici.trenutniKorisnik.getPare());
        lbWelcome.setText("Dobrodosli, " + Korisnici.trenutniKorisnik.getIme());
        if (Korisnici.trenutniKorisnik.getLoyalty()) {
            lblCard.setText(("Imate loyalty card i pravo na popust od 10%"));
        }
        else {
            lblCard.setText(("Nemate loyalty card i pravo na popust od 10%"));
        }
        setTitle("Kozmeticki salon");
        setSize(700, 700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setContentPane(kMeniPanel);
        setVisible(true);
        odjavaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Korisnici.logout();
                LoginFrame log = new LoginFrame();
                dispose();
            }
        });
        pregledIzvrsenihTretmanaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                KlijentPrikazIzvrsenih frejm = new KlijentPrikazIzvrsenih();
            }
        });
        pregledZakazanihTretmanaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                KlijentPrikazNeizvrsenih neizvrseni = new KlijentPrikazNeizvrsenih();
            }
        });
        zakaziTretmanButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Tretmani.zakaziOnline();
            }
        });
    }

    public JPanel getKMeniPanel() {
        return kMeniPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        kMeniPanel = new JPanel();
        kMeniPanel.setLayout(new GridBagLayout());
        pregledIzvrsenihTretmanaButton = new JButton();
        pregledIzvrsenihTretmanaButton.setText("Pregled prethodnih tretmana");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kMeniPanel.add(pregledIzvrsenihTretmanaButton, gbc);
        odjavaButton = new JButton();
        odjavaButton.setText("Odjava");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kMeniPanel.add(odjavaButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.VERTICAL;
        kMeniPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        kMeniPanel.add(spacer2, gbc);
        zakaziTretmanButton = new JButton();
        zakaziTretmanButton.setText("Zakazi Tretman");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kMeniPanel.add(zakaziTretmanButton, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        kMeniPanel.add(spacer3, gbc);
        pregledZakazanihTretmanaButton = new JButton();
        pregledZakazanihTretmanaButton.setText("Pregled buducih tretmana");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kMeniPanel.add(pregledZakazanihTretmanaButton, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        kMeniPanel.add(spacer4, gbc);
        lbWelcome = new JLabel();
        lbWelcome.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        kMeniPanel.add(lbWelcome, gbc);
        lbLoyalty = new JLabel();
        lbLoyalty.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        kMeniPanel.add(lbLoyalty, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        kMeniPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        kMeniPanel.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        kMeniPanel.add(spacer7, gbc);
        lblCard = new JLabel();
        lblCard.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        kMeniPanel.add(lblCard, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return kMeniPanel;
    }

}
