package gui;

import korisnici.Korisnici;
import korisnici.Kozmeticar;
import tretmani.Tretmani;
import tretmani.ZakazanTretman;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

public class KozmeticarRaspored extends JFrame {
    private JScrollPane tabelaPanel;
    private JPanel rasporedPanel;

    public KozmeticarRaspored() {
        setTitle("Danasnji raspored");
        setSize(500, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ArrayList<ZakazanTretman> zakazani = Tretmani.prikaziRaspored((Kozmeticar) Korisnici.trenutniKorisnik, LocalDate.now());
        String[] header = {"Od", "Do", "Naziv tretmana", "Klijent", "Cena", "Status"};
        Object[][] sadrzaj = new Object[zakazani.size()][6];
        int i = 0;
        for (ZakazanTretman zakazan : zakazani) {
            sadrzaj[i][0] = zakazan.getDatum_i_vreme().format(DateTimeFormatter.ofPattern("HH:00"));
            sadrzaj[i][1] = (zakazan.getDatum_i_vreme().plus(zakazan.getVrsta().getTrajanje())).format(DateTimeFormatter.ofPattern("HH:mm"));
            sadrzaj[i][2] = zakazan.getNaziv();
            sadrzaj[i][3] = zakazan.getKlijent().getIme() + " " + zakazan.getKlijent().getPrezime();
            sadrzaj[i][4] = zakazan.getCena();
            sadrzaj[i][5] = zakazan.getStatus();
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(sadrzaj, header) {
            public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
            }
        };
        ;
        model.setColumnIdentifiers(header);
        JTable tabelaIspis = new JTable(model);
        tabelaPanel.setViewportView(tabelaIspis);
        setContentPane(rasporedPanel);
        tabelaIspis.setFocusable(false);
        tabelaIspis.setRowSelectionAllowed(false);
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rasporedPanel = new JPanel();
        rasporedPanel.setLayout(new GridBagLayout());
        tabelaPanel = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        rasporedPanel.add(tabelaPanel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rasporedPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        rasporedPanel.add(spacer2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rasporedPanel;
    }

}
