package gui;

import korisnici.Korisnici;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class KozmeticarMeni extends JFrame {
    private JButton rasporedZaDanasButton;
    private JButton dodeljeniTretmaniButton;
    private JButton odjavaButton;
    private JLabel lblWelcome;
    private JPanel kozmeticarPanel;

    public KozmeticarMeni() {
        lblWelcome.setText("Dobrodosli, " + Korisnici.trenutniKorisnik.getIme());
        setTitle("Kozmeticki salon");
        setSize(700, 700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setContentPane(kozmeticarPanel);
        setVisible(true);

        odjavaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Korisnici.logout();
                LoginFrame log = new LoginFrame();
                dispose();
            }
        });
        rasporedZaDanasButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                KozmeticarRaspored raspored = new KozmeticarRaspored();
            }
        });
        dodeljeniTretmaniButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                KozmeticarSviZaduzeni zaduzeni = new KozmeticarSviZaduzeni();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        kozmeticarPanel = new JPanel();
        kozmeticarPanel.setLayout(new GridBagLayout());
        rasporedZaDanasButton = new JButton();
        rasporedZaDanasButton.setText("Raspored za danas");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kozmeticarPanel.add(rasporedZaDanasButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kozmeticarPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        kozmeticarPanel.add(spacer2, gbc);
        dodeljeniTretmaniButton = new JButton();
        dodeljeniTretmaniButton.setText("Dodeljeni tretmani");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kozmeticarPanel.add(dodeljeniTretmaniButton, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        kozmeticarPanel.add(spacer3, gbc);
        odjavaButton = new JButton();
        odjavaButton.setText("Odjava");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        kozmeticarPanel.add(odjavaButton, gbc);
        lblWelcome = new JLabel();
        lblWelcome.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        kozmeticarPanel.add(lblWelcome, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return kozmeticarPanel;
    }
}
