package gui;

import korisnici.Korisnici;
import korisnici.Korisnik;
import salon.*;
import tretmani.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;

public class LoginFrame extends JFrame {
    private JLabel lbUsername;
    private JPasswordField tfPassword;
    private JButton ulogujSeButton;
    private JButton registrujSeButton;
    private JPanel loginPanel;
    private JTextField tfKorisnickoIme;

    public LoginFrame() {
        setTitle("Kozmeticki salon");
        setSize(700, 700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        RegForm reg = new RegForm();
        setContentPane(loginPanel);
        setVisible(true);
        ulogujSeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String korisnickoIme = tfKorisnickoIme.getText();
                String sifra = tfPassword.getText();

                boolean uspeh = Korisnici.login(korisnickoIme, sifra);

                if (uspeh) {
                    String poruka = "Dobrodosli, " + Korisnici.trenutniKorisnik.getIme();
                    JOptionPane.showMessageDialog(null, poruka, "Login uspesan", JOptionPane.INFORMATION_MESSAGE);
                    if (Korisnici.trenutniKorisnik.getTip() == Korisnik.tipKorisnika.KLIJENT) {
                        KorisnikMeni kmeni = new KorisnikMeni();
                    }
                    if (Korisnici.trenutniKorisnik.getTip() == Korisnik.tipKorisnika.RECEPCIONER) {
                        RecepcionerMeni rmeni = new RecepcionerMeni();
                    }
                    if (Korisnici.trenutniKorisnik.getTip() == Korisnik.tipKorisnika.KOZMETICAR) {
                        KozmeticarMeni komeni = new KozmeticarMeni();
                    }
                    if (Korisnici.trenutniKorisnik.getTip() == Korisnik.tipKorisnika.MENADZER) {
                        MenadzerMeni mmeni = new MenadzerMeni();
                    }
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Neki od podataka nije pravilno unet", "Login neuspesan", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        registrujSeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                reg.setVisible(true);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        loginPanel = new JPanel();
        loginPanel.setLayout(new GridBagLayout());
        loginPanel.setMinimumSize(new Dimension(150, 50));
        loginPanel.setPreferredSize(new Dimension(150, 50));
        final JLabel label1 = new JLabel();
        label1.setText("Sifra: ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        loginPanel.add(label1, gbc);
        lbUsername = new JLabel();
        lbUsername.setText("Korisnicko ime:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        loginPanel.add(lbUsername, gbc);
        tfPassword = new JPasswordField();
        tfPassword.setPreferredSize(new Dimension(150, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        loginPanel.add(tfPassword, gbc);
        ulogujSeButton = new JButton();
        ulogujSeButton.setText("Uloguj se");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        loginPanel.add(ulogujSeButton, gbc);
        registrujSeButton = new JButton();
        registrujSeButton.setText("Registruj se");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        loginPanel.add(registrujSeButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        loginPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        loginPanel.add(spacer2, gbc);
        tfKorisnickoIme = new JTextField();
        tfKorisnickoIme.setPreferredSize(new Dimension(150, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        loginPanel.add(tfKorisnickoIme, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        loginPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        loginPanel.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        loginPanel.add(spacer5, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return loginPanel;
    }

}
