package gui;

import korisnici.Korisnici;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MenadzerMeni extends JFrame {
    private JButton odjavaButton;
    private JButton buduciTretmaniButton;
    private JButton prethodniTretmaniButton;
    private JButton dodajZaposlenogButton;
    private JLabel lblWelcome;
    private JPanel menadzerPanel;
    private JButton sviKorisniciButton;
    private JButton tipoviTretmanaButton;
    private JButton vrsteTretmanaButton;
    private JButton izvestajKozmeticariButton;
    private JButton izvestajOtkazivanjeButton;
    private JButton izvestajVrsteTretmanaButton;
    private JButton izvestajLoyaltyButton;

    public MenadzerMeni() {
        lblWelcome.setText("Dobrodosli, " + Korisnici.trenutniKorisnik.getIme());
        setTitle("Kozmeticki salon");
        setSize(700, 700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setContentPane(menadzerPanel);
        setVisible(true);
        odjavaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Korisnici.logout();
                LoginFrame log = new LoginFrame();
                dispose();
            }
        });
        buduciTretmaniButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SalonZakazani zakazani = new SalonZakazani();
            }
        });
        prethodniTretmaniButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                MenadzerPrethodni prethodni = new MenadzerPrethodni();
            }
        });
        dodajZaposlenogButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                RegZaposlenog regzap = new RegZaposlenog();
            }
        });
        sviKorisniciButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SviKorisnici svik = new SviKorisnici();
            }
        });
        tipoviTretmanaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                MenadzerTipovi tipovi = new MenadzerTipovi();
            }
        });
        vrsteTretmanaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                MenadzerVrste vrste = new MenadzerVrste();
            }
        });
        izvestajKozmeticariButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                KozmeticariIzvestaj kizvestaj = new KozmeticariIzvestaj();
            }
        });
        izvestajOtkazivanjeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                IzvestajOtkazivanje iot = new IzvestajOtkazivanje();
            }
        });
        izvestajVrsteTretmanaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                IzvestajVrste iv = new IzvestajVrste();
            }
        });
        izvestajLoyaltyButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                IzvestajLoyalty il = new IzvestajLoyalty();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        menadzerPanel = new JPanel();
        menadzerPanel.setLayout(new GridBagLayout());
        odjavaButton = new JButton();
        odjavaButton.setText("Odjava");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menadzerPanel.add(odjavaButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.VERTICAL;
        menadzerPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        menadzerPanel.add(spacer2, gbc);
        buduciTretmaniButton = new JButton();
        buduciTretmaniButton.setText("Buduci tretmani");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menadzerPanel.add(buduciTretmaniButton, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        menadzerPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        menadzerPanel.add(spacer4, gbc);
        prethodniTretmaniButton = new JButton();
        prethodniTretmaniButton.setText("Prethodni tretmani");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menadzerPanel.add(prethodniTretmaniButton, gbc);
        dodajZaposlenogButton = new JButton();
        dodajZaposlenogButton.setText("Dodaj zaposlenog");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menadzerPanel.add(dodajZaposlenogButton, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        menadzerPanel.add(spacer5, gbc);
        lblWelcome = new JLabel();
        lblWelcome.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        menadzerPanel.add(lblWelcome, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        menadzerPanel.add(spacer6, gbc);
        sviKorisniciButton = new JButton();
        sviKorisniciButton.setText("Svi korisnici");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menadzerPanel.add(sviKorisniciButton, gbc);
        tipoviTretmanaButton = new JButton();
        tipoviTretmanaButton.setText("Tipovi tretmana");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menadzerPanel.add(tipoviTretmanaButton, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menadzerPanel.add(spacer7, gbc);
        vrsteTretmanaButton = new JButton();
        vrsteTretmanaButton.setText("Vrste tretmana");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menadzerPanel.add(vrsteTretmanaButton, gbc);
        izvestajKozmeticariButton = new JButton();
        izvestajKozmeticariButton.setText("Izvestaj Kozmeticari");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menadzerPanel.add(izvestajKozmeticariButton, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menadzerPanel.add(spacer8, gbc);
        izvestajOtkazivanjeButton = new JButton();
        izvestajOtkazivanjeButton.setText("Izvestaj Statusi");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menadzerPanel.add(izvestajOtkazivanjeButton, gbc);
        izvestajVrsteTretmanaButton = new JButton();
        izvestajVrsteTretmanaButton.setText("Izvestaj Vrste tretmana");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menadzerPanel.add(izvestajVrsteTretmanaButton, gbc);
        izvestajLoyaltyButton = new JButton();
        izvestajLoyaltyButton.setText("Izvestaj Loyalty");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        menadzerPanel.add(izvestajLoyaltyButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return menadzerPanel;
    }

}
