package gui;

import korisnici.Korisnici;
import korisnici.Korisnik;
import korisnici.Kozmeticar;
import korisnici.Zaposleni;
import salon.Saloni;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class RegZaposlenog extends JFrame {
    private JTextField tfUsername;
    private JTextField tfPass;
    private JTextField tfIme;
    private JTextField tfPrezime;
    private JComboBox cbPol;
    private JTextField tfAdresa;
    private JTextField tfBroj;
    private JSpinner spGodine;
    private JComboBox cbSprema;
    private JButton registrujZaposlenogButton;
    private JPanel regZapPanel;
    private JComboBox cbTip;

    public RegZaposlenog() {
        setContentPane(regZapPanel);
        setTitle("Registracija");
        setSize(800, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        for (Korisnik.tipKorisnika tip : Korisnik.tipKorisnika.values()) {
            if (tip != Korisnik.tipKorisnika.KLIJENT) {
                cbTip.addItem(tip);
            }
        }
        for (Zaposleni.nivoSpreme nivo : Zaposleni.nivoSpreme.values()) {
            cbSprema.addItem(nivo);
        }
        setVisible(true);

        registrujZaposlenogButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Korisnik korisnik = new Korisnik();
                if ((Korisnik.tipKorisnika) cbTip.getSelectedItem() != Korisnik.tipKorisnika.KOZMETICAR) {
                    korisnik = new Zaposleni(tfIme.getText(), tfPrezime.getText(), (String) cbPol.getSelectedItem(), tfBroj.getText(), tfAdresa.getText(), tfUsername.getText(), tfPass.getText(),
                            (Zaposleni.nivoSpreme) cbSprema.getSelectedItem(), (int) spGodine.getValue(), (Korisnik.tipKorisnika) cbTip.getSelectedItem());
                } else {
                    korisnik = new Kozmeticar(tfIme.getText(), tfPrezime.getText(), (String) cbPol.getSelectedItem(), tfBroj.getText(), tfAdresa.getText(), tfUsername.getText(), tfPass.getText(),
                            (Zaposleni.nivoSpreme) cbSprema.getSelectedItem(), (int) spGodine.getValue());
                }

                boolean uspeh = Korisnici.dodajKorisnika(korisnik);

                if (uspeh) {
                    JOptionPane.showMessageDialog(null, "Registracija uspesna", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
                    Saloni.sacuvajSalonPodatke(Saloni.trenutniSalon);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Korisnik sa zadatim korisnivkim imenom vec postoji", "Registracija neuspesna", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        regZapPanel = new JPanel();
        regZapPanel.setLayout(new GridBagLayout());
        tfUsername = new JTextField();
        tfUsername.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(tfUsername, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        regZapPanel.add(spacer2, gbc);
        tfPass = new JTextField();
        tfPass.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(tfPass, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        regZapPanel.add(spacer3, gbc);
        tfIme = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(tfIme, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        regZapPanel.add(spacer4, gbc);
        tfPrezime = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(tfPrezime, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        regZapPanel.add(spacer5, gbc);
        cbPol = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("");
        defaultComboBoxModel1.addElement("Musko");
        defaultComboBoxModel1.addElement("Zensko");
        defaultComboBoxModel1.addElement("Drugo");
        cbPol.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(cbPol, gbc);
        tfAdresa = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(tfAdresa, gbc);
        tfBroj = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(tfBroj, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        regZapPanel.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.VERTICAL;
        regZapPanel.add(spacer7, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Korisnicko ime:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        regZapPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Sifra:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        regZapPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Ime:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        regZapPanel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Prezime:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        regZapPanel.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Pol:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        regZapPanel.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Adresa:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        regZapPanel.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Broj telefona:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 12;
        gbc.anchor = GridBagConstraints.WEST;
        regZapPanel.add(label7, gbc);
        spGodine = new JSpinner();
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(spGodine, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Godina staza:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        regZapPanel.add(label8, gbc);
        cbSprema = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        cbSprema.setModel(defaultComboBoxModel2);
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(cbSprema, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Nivo strucne spreme:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        regZapPanel.add(label9, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 13;
        gbc.fill = GridBagConstraints.VERTICAL;
        regZapPanel.add(spacer8, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(spacer10, gbc);
        registrujZaposlenogButton = new JButton();
        registrujZaposlenogButton.setText("Registruj zaposlenog");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 14;
        gbc.gridwidth = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(registrujZaposlenogButton, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("Tip zaposlenog:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        regZapPanel.add(label10, gbc);
        cbTip = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        regZapPanel.add(cbTip, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return regZapPanel;
    }

}
